-- CreateTable
CREATE TABLE "Users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "name" STRING NOT NULL,

    CONSTRAINT "Users_pkey" PRIMARY KEY ("id")
);
