-- CreateTable
CREATE TABLE "Tasks" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "description" STRING NOT NULL,
    "priority" STRING NOT NULL,
    "done" BOOL NOT NULL,

    CONSTRAINT "Tasks_pkey" PRIMARY KEY ("id")
);
